
DROP TABLE IF EXISTS rb_logs CASCADE;
DROP TABLE IF EXISTS rb_notifications CASCADE;
DROP TABLE IF EXISTS rb_bookings CASCADE;
DROP TABLE IF EXISTS rb_rooms CASCADE;
DROP TABLE IF EXISTS rb_users CASCADE;

CREATE TABLE IF NOT EXISTS rb_users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) DEFAULT 'user',
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rb_rooms (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  capacity INTEGER NOT NULL,
  location VARCHAR(255) NOT NULL,
  "imageUrl" TEXT
);

CREATE TABLE IF NOT EXISTS rb_bookings (
  id SERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL REFERENCES rb_users(id) ON DELETE CASCADE,
  "roomId" INTEGER REFERENCES rb_rooms(id) ON DELETE CASCADE,
  date VARCHAR(50) NOT NULL,
  "startTime" VARCHAR(50) NOT NULL,
  "endTime" VARCHAR(50) NOT NULL,
  status VARCHAR(50) DEFAULT 'confirmed',
  "emergencyReason" TEXT,
  "resolutionReason" TEXT
);

CREATE TABLE IF NOT EXISTS rb_notifications (
  id SERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL REFERENCES rb_users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  type VARCHAR(50) DEFAULT 'info',
  read BOOLEAN DEFAULT false,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rb_logs (
  id SERIAL PRIMARY KEY,
  action VARCHAR(255) NOT NULL,
  details TEXT NOT NULL,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
